version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_yaya
    environment:
      POSTGRES_USER: yaya
      POSTGRES_PASSWORD: zxcv4567
      POSTGRES_DB: LineBotScript
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
