
events {
    worker_connections 1024; 
}

# HTTP 配置
http {
    include       /etc/nginx/mime.types;  # 包含 MIME 类型
    default_type application/octet-stream;  # 默认类型

    sendfile        on;  # 启用高效文件传输
    keepalive_timeout 65;  # 设置保持活动超时


    server {
        listen 80; 
        server_name yaya200.live www.yaya200.live; 
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;  # 监听 HTTPS 端口
        server_name yaya200.live www.yaya200.live;  # 指定域名

        # SSL 证书配置
        ssl_certificate /etc/letsencrypt/live/yaya200.live/fullchain.pem;  # 证书文件
        ssl_certificate_key /etc/letsencrypt/live/yaya200.live/privkey.pem;  # 私钥文件

        # SSL 优化配置（可选）
        ssl_protocols       TLSv1.2 TLSv1.3;  # 启用的 SSL 协议
        ssl_ciphers         HIGH:!aNULL:!MD5;  # SSL 加密套件
        ssl_prefer_server_ciphers on;  # 首选服务器加密套件

        location / {
            proxy_pass http://backend:8080;  # 反向代理到后端服务
            proxy_set_header Host $host;  # 设置主机头
            proxy_set_header X-Real-IP $remote_addr;  # 设置真实 IP
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # 转发 IP
            proxy_set_header X-Forwarded-Proto $scheme;  # 转发协议
        }
	
	location /assets/ {
	    alias /usr/share/nginx/html/assets/;  # 使用映射的路徑	
	}	

        location /.well-known/acme-challenge/ {
            root /var/www/html;  # Certbot 用于验证的目录
        }
    }
}
