basePath: /
info:
  contact: {}
  description: This is a sample server for Line Bot API.
  title: Line Bot API
  version: "1.0"
paths:
  /nodes/create:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Create a new node with the specified type and range
      parameters:
      - description: nodeTitle for the Node
        in: formData
        name: nodeTitle
        required: true
        type: string
      - description: nodeType for the Node
        in: formData
        name: nodeType
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created Node
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Create Node fail
          schema:
            additionalProperties: true
            type: object
      summary: Create a new node
      tags:
      - nodes
  /nodes/delete:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Delete a new node with the specified ID
      parameters:
      - description: nodeID for the Node
        in: formData
        name: nodeId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Successfully delete Node
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Delete Node fail
          schema:
            additionalProperties: true
            type: object
      summary: Delete a new node
      tags:
      - nodes
  /nodes/next:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Update the next node ID for the specified node
      parameters:
      - description: Node ID
        in: formData
        name: nodeId
        required: true
        type: integer
      - description: Next Node ID
        in: formData
        name: nodeNext
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Updated node
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Node is not exist
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to update node
          schema:
            additionalProperties: true
            type: object
      summary: Update the next node of a specific node
      tags:
      - nodes
  /nodes/previous:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Update the previous node ID for the specified node
      parameters:
      - description: Node ID
        in: formData
        name: nodeId
        required: true
        type: integer
      - description: Previous Node ID
        in: formData
        name: nodePrevious
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Updated node
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Node is not exist
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to update node
          schema:
            additionalProperties: true
            type: object
      summary: Update the previous node of a specific node
      tags:
      - nodes
  /nodes/title:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Update the title for the specified node
      parameters:
      - description: Node ID
        in: formData
        name: nodeId
        required: true
        type: integer
      - description: New Node Title
        in: formData
        name: nodeTitle
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Updated node
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Node is not exist
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to update node
          schema:
            additionalProperties: true
            type: object
      summary: Update the title of a specific node
      tags:
      - nodes
swagger: "2.0"
